[package]
name = "xtask"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
serde_json.workspace = true
base64.workspace = true
libc.workspace = true
terminator-core.workspace = true
tempfile = "3"
clap = { version = "4", features = ["derive"] }
xshell = "0.2"
plist = "1"
tar = "0.4"
flate2 = "1"
image = { version = "0.25", default-features = false, features = ["png"] }

[target.'cfg(target_os = "linux")'.dependencies]
x11rb = { version = "0.13", features = ["xtest"] }

[target.'cfg(target_os = "macos")'.dependencies]
core-graphics = { version = "0.23", features = ["elcapitan"] }
core-foundation = "0.9"

[dependencies.tungstenite]
version = "0.28"
default-features = false
features = ["handshake"]
