[package]
name = "terminator-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
base64.workspace = true
directories = "6"
libc.workspace = true
toml_edit = { version = "0.25", features = ["serde"] }

[dev-dependencies]
tempfile = "3"

[dependencies.sysinfo]
version = "0.38"
default-features = false
features = ["system"]

[dependencies.url]
version = "2"
